FROM node:20-alpine3.20 AS builder

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm install --force

COPY . .

RUN npm run build

FROM node:20-alpine3.20 AS runner
WORKDIR /usr/src/app

COPY --from=builder /usr/src/app/.next ./.next
COPY --from=builder /usr/src/app/package*.json ./

RUN npm install --omit=dev --legacy-peer-deps --force

EXPOSE 80

CMD ["npm","run", "start"]